server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pawan
    url: jdbc:mysql://localhost:3306/comment
    username: pawan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
   multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 200MB
    max-request-size: 215MB

files:
  storage: C:/image/
